[package]
name = "quickjs-wasm-sys"
version = "0.1.2"
authors.workspace = true
edition.workspace = true 
license.workspace = true
description = "Rust bindings for Wasm build of QuickJS"
homepage = "https://github.com/Shopify/javy/tree/main/crates/quickjs-wasm-sys"
repository = "https://github.com/Shopify/javy/tree/main/crates/quickjs-wasm-sys"
categories = ["external-ffi-bindings"]

[dependencies]

[build-dependencies]
cc = "1.0"
bindgen = "0.59"
walkdir = "2"
