[package]
name = "quickjs-wasm-sys"
version = "1.0.0"
authors.workspace = true
edition.workspace = true 
license.workspace = true
description = "Rust bindings for Wasm build of QuickJS"
homepage = "https://github.com/bytecodealliance/javy/tree/main/crates/quickjs-wasm-sys"
repository = "https://github.com/bytecodealliance/javy/tree/main/crates/quickjs-wasm-sys"
categories = ["external-ffi-bindings"]

[dependencies]

[build-dependencies]
cc = "1.0"
bindgen = "0.60"
walkdir = "2"
anyhow = "1.0.71"
reqwest = { version = "0.11.18", features = ["blocking"] }
