# Tests extra CLI features and their dependency with plugin features.
name: Test CLI Features
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cli:
    name: Test CLI Features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci-shared-setup

      - name: Build test-plugin
        run: |
          cargo build --package=javy-test-plugin --release --target=wasm32-wasip1
          CARGO_PROFILE_RELEASE_LTO=off cargo build --package=javy-cli --release
          target/release/javy init-plugin target/wasm32-wasip1/release/test_plugin.wasm -o crates/runner/test_plugin.wasm

      - name: Test `experimental_event_loop`
        run: |
          cargo build --package=javy-plugin --target=wasm32-wasip1 --release --features=experimental_event_loop
          cargo test --package=javy-cli --features=experimental_event_loop --release -- --nocapture
